### ISSUE TITLE
It does not work

### ISSUE THREAD

**Issue by ricnar456** [zhefox/Bindiff_for_IDA9.0#1]
It  does not  work

![image](https://github.com/user-attachments/assets/6b7b07a9-99a0-45c3-aeaa-8362732eebc6)

![image](https://github.com/user-attachments/assets/e2fcb355-9883-4922-8414-284a5e1df68f)

![image](https://github.com/user-attachments/assets/6dd13103-bdbb-4d63-8ab9-dc1e4e5e93be)

**Comment by ricnar456** [comment]
the menu BINDIFF appears in plugins, but IDA crashes when is used.

**Comment by zhefox** [comment]
it's not support 240925,just for 240807,I will upload the latest version later, but it only supports x64. You need to delete the 32-bit file and keep only the 64 bit file.

**Comment by zhefox** [comment]
https://github.com/zhefox/Bindiff_for_IDA9.0/tree/IDA9.0RC1

**Comment by ricnar456** [comment]
thanks it worked
